# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder "C:\\", "/c"
  name = "main-vm"
  config.vm.define name, primary: true do |cfg|
    cfg.vm.hostname = name
    cfg.vm.network "private_network", ip: "10.10.10.10"
    cfg.vm.network "forwarded_port", guest: 8081, host: 8081
    cfg.vm.network "forwarded_port", guest: 22, host: 2200
    cfg.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--vram", "32", '--clipboard', 'bidirectional']
      vb.name = name
    end
    cfg.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.install_mode = "pip"
      ansible.pip_install_cmd = "curl -s https://bootstrap.pypa.io/get-pip.py | sudo python3"
      ansible.extra_vars = {
        os: {
          dist: "debian",
          version: 9
        },
        user: {
          name: "cq2n-iwym",
          password: "$6$N4.rjdBkS3Y/Od1U$77YfWpOFu8xbrv14Qot/RsKEfGexlb/TggyjMAz37oAn5knI7h2gwHcw0ZsVkmPGtGbr5A02uglrJLHsV0rF90"
        },
        xmonad: {
          install: false
        },
        tmux: {
          install_method: "apt"
        }
      }
    end
  end
end
