# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.synced_folder "C:\\", "/c"
  stretch_name = "vm-stretch"
  config.vm.define stretch_name, primary: true do |cfg|
    cfg.disksize.size = "100GB"
    cfg.vm.hostname = stretch_name
    cfg.vm.box = "debian/stretch64"
    cfg.vm.network "private_network", ip: "10.10.10.11"
    cfg.vm.network "forwarded_port", guest: 8080, host: 8081
    cfg.vm.network "forwarded_port", guest: 22, host: 2201
    cfg.vm.provider "virtualbox" do |vb|
      vb.gui = false
      # vb.gui = true
      vb.memory = "10240"
      vb.customize ["modifyvm", :id, "--vram", "32", '--clipboard', 'bidirectional']
      vb.name = stretch_name
    end
    cfg.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.install_mode = "pip"
      ansible.pip_install_cmd = "sudo apt install python-pip -y"
      ansible.extra_vars = {
        has_root: true,
        os: {
          dist: "debian",
          version: 9
        },
        user: {
          name: "cq2n-iwym",
          create: true,
          sudoer: true,
          password: "$6$N4.rjdBkS3Y/Od1U$77YfWpOFu8xbrv14Qot/RsKEfGexlb/TggyjMAz37oAn5knI7h2gwHcw0ZsVkmPGtGbr5A02uglrJLHsV0rF90",
          ssh_public_key: "C:\\Users\\cq2n-iwym\\.ssh\\id_ed25519.pub"
        },
        python: {
          build: true,
          version: "3.9.1"
        },
        xmonad: {
          install: false
        },
        tmux: {
          install_method: "build"
        },
        at_company: true
      }
    end
  end
  ##############################################################################
  buster_name = "buster"
  config.vm.define buster_name, primary: false do |cfg|
    cfg.disksize.size = "100GB"
    cfg.vm.hostname = buster_name
    cfg.vm.box = "debian/buster64"
    cfg.vm.network "private_network", ip: "10.10.10.12"
    cfg.vm.network "forwarded_port", guest: 8080, host: 8082
    cfg.vm.network "forwarded_port", guest: 22, host: 2202
    cfg.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "10240"
      vb.customize ["modifyvm", :id, "--vram", "32", '--clipboard', 'bidirectional']
      vb.name = buster_name
    end
    cfg.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.install_mode = "pip"
      ansible.pip_install_cmd = "apt install -y python3-distutils && curl https://bootstrap.pypa.io/get-pip.py | sudo python3"
      ansible.extra_vars = {
        has_root: true,
        os: {
          dist: "debian",
          version: 10
        },
        user: {
          name: "cq2n-iwym",
          create: true,
          sudoer: true,
          password: "$6$N4.rjdBkS3Y/Od1U$77YfWpOFu8xbrv14Qot/RsKEfGexlb/TggyjMAz37oAn5knI7h2gwHcw0ZsVkmPGtGbr5A02uglrJLHsV0rF90",
          ssh_public_key: "/c/Users/cq2n-iwym/.ssh/id_ed25519.pub"
        },
        python: {
          build: false,
        },
        xmonad: {
          install: false
        },
        tmux: {
          install_method: "apt"
        },
        at_company: true
      }
    end
  end
end
