---
- hosts: all
  become: "{{ has_root }}"
  environment:
    SSL_CERT_DIR: /etc/ssl/certs
  roles:
    # Tools
    - role: devtool
      tags: devtool
      when: has_root

    - role: python
      tags: python
      when: has_root and python.build

    - role: node
      tags: node
      when: has_root

    - role: java
      tags: java
      when: has_root

    # non-grobal settings
    - role: zsh
      tags: zsh
      when: has_root

    - role: tmux
      tags: tmux
      when: has_root

    - role: neovim
      tags: neovim

    # User settings
    - role: dotfiles
      tags: dotfiles

    - role: zsh_conf
      tags: zsh

    - role: tmux_conf
      tags: tmux

    - role: neovim_conf
      tags: neovim

    - role: xmonad_conf
      tags: xmonad
      when: xmonad.install|default(false)
