---
- hosts: all
  become: yes
  environment:
    SSL_CERT_DIR: /etc/ssl/certs
  roles:
    - role: devtool
      tags: devtool

    - role: desktop
      tags: desktop

    - role: python
      tags: python
      # TODO 専用の変数でやる
      when: os.dist=="debian" and os.version <= 9

    - role: node
      tags: node

    - role: company
      tags: company
      when: at_company|default(false)

    # non-grobal settings
    - role: add_user
      tags: add_user

    - role: zsh
      tags: zsh

    - role: tmux
      tags: tmux

    - role: neovim
      tags: neovim

    - role: dotfiles
      tags: dotfiles

    - role: xmonad
      tags: xmonad
      when: xmonad.install|default(false)
