---
- hosts: all
  become: "{{ has_root }}"
  environment:
    SSL_CERT_DIR: /etc/ssl/certs
  roles:
    - role: basic
      tags: basic
    - role: develop
      tags: develop
    - role: user_conf
      tags: user_conf
