#!/bin/bash
set -eu
set -o pipefail

FCMD=goto
DCMD=cd
while [ $# -gt 0 ]; do
  case "$1" in
    -c|--cmd)
      FCMD="$2"
      shift
      ;;
    -d|--dcmd)
      DCMD="$2"
      shift
      ;;
    *)
      ;;
  esac
  shift
done

FD_OPTS=(
  --hidden
  --no-ignore
  --exclude .git
  --exclude .hie
  --exclude .direnv
  --exclude dist-newstyle
  --exclude .stack-work
)
FZF_OPTS=(
  --preview "vifm-viewer {}"
  --preview-window right:50%:noborder
)
TARGET=$(realpath $(fd "${FD_OPTS[@]}" | fzf "${FZF_OPTS[@]}"))
if [[ -d "${TARGET}" ]]; then
  echo "${DCMD} '${TARGET}'"
else
  echo "${FCMD} '${TARGET}'"
fi
