# This file is generated by ansible. Do not edit manually.
# Edit $HOME/.zshenv.local instead.
source-if-exists() {
  [ -e $1 ] && . $1
}
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/go/bin:$PATH
source-if-exists $HOME/.ghcup/env
source-if-exists $HOME/.cargo/env
source-if-exists $HOME/.opam/opam-init/init.zsh
source-if-exists $HOME/.nix-profile/etc/profile.d/nix.sh
source-if-exists $HOME/.autojump/etc/profile.d/autojump.sh
source-if-exists $HOME/.zshenv.local
