#!/bin/sh
set -eu
# stack install --local-bin-path ./ && xmonad --restart
cabal install \
  --installdir=./ \
  --overwrite-policy=always \
  --install-method=copy \
  --write-ghc-environment-files=always
cabal exec -- xmonad --restart
# xmonad --restart
