- name: Install .xmonad
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user.name }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 'preserve'
  loop:
    - .xmonad/
