- name: Check whether python-{{ python.version }} is installed
  shell:
    # drop minor version number by 'splitext | first'
    cmd: "which python{{ python.version | splitext | first }}"
  register: which_python
  changed_when: false
  ignore_errors: true

- set_fact:
    build_python:
      "{{ python.build|default(false) and
          not which_python.skipped|default(false) and
          which_python.rc != 0 }}"

- name: Install python dependencies
  apt:
    name:
    - build-essential
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm-dev
    - libnss3-dev
    - libssl-dev
    - libreadline-dev
    - libffi-dev
    - wget
    - curl
  when: build_python

- name: Unarchive python source
  unarchive:
    src: "https://www.python.org/ftp/python/{{ python.version }}/Python-{{ python.version }}.tar.xz"
    dest: /root
    remote_src: true
  when: build_python

- name: Install python
  shell:
    chdir: "/root/Python-{{ python.version }}"
    cmd: |
      ./configure --enable-optimizations
      make -j4
      sudo make altinstall
    creates: "/usr/local/bin/python{{ python.version }}"
  when: build_python
