- name: Install python dependencies
  apt:
    name:
    - build-essential
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm-dev
    - libnss3-dev
    - libssl-dev
    - libreadline-dev
    - libffi-dev
    - wget
    - curl

- name: Download python source
  get_url:
    url: "https://www.python.org/ftp/python/{{ python.version }}/Python-{{ python.version }}.tar.xz"
    dest: "/root/Python-{{ python.version }}.tar.xz"

- name: Unarchive python source
  unarchive:
    src: "/root/Python-{{ python.version }}.tar.xz"
    dest: /root
    remote_src: yes

- name: Install python
  shell:
    chdir: "/root/Python-{{ python.version }}"
    cmd: |
      ./configure --enable-optimizations
      make -j4
      sudo make altinstall
    creates: "/usr/local/bin/python{{ python.version }}"
