- name: "Check whether python-{{ python.version }} is installed"
  shell:
    # drop minor version number by 'splitext | first'
    cmd: "which python{{ python.version | splitext | first }}"
  register: which_python
  when: python.build|default(false)
  changed_when: false
  ignore_errors: true
  tags:
    - python

- set_fact:
    build_python:
      "{{ python.build|default(false) and
          not which_python.skipped|default(false) and
          which_python.rc != 0 }}"
  tags:
    - python

- name: Install python dependencies
  apt:
    name:
    - build-essential
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm-dev
    - libnss3-dev
    - libssl-dev
    - libreadline-dev
    - libffi-dev
    - wget
    - curl
  when: build_python
  tags:
    - python

- name: Unarchive python source
  unarchive:
    src: "https://www.python.org/ftp/python/{{ python.version }}/Python-{{ python.version }}.tar.xz"
    dest: /root
    remote_src: true
  when: build_python
  tags:
    - python

- name: Install python
  shell:
    chdir: "/root/Python-{{ python.version }}"
    cmd: |
      ./configure --enable-optimizations
      make -j4
      sudo make altinstall
    creates: "/usr/local/bin/python{{ python.version }}"
  when: build_python
  tags:
    - python

- set_fact:
    # pip3.X if python.version is 3.X.Y
    # pip3 if python.version is undefined
    pip_cmd: "pip{{ python.version|default('3.0')|splitext|first }}"
  tags:
    - python
