
resolver: lts-11.17

packages:
- .

extra-deps:
- nvim-hs-1.0.0.2
- nvim-hs-contrib-1.0.0.0
- extensible-0.4.7
- rio-0.1.5.0
- typed-process-0.2.2.0
- unliftio-0.2.7.0
- github: Hogeyama/ghc-mod-nvim
  commit: c8350e3
- github: Hogeyama/ghcid-nvim-simple
  commit: 21ca24a
#- ./nvim-hs-libs/ghcid-nvim-simple
- ./nvim-hs-libs/nvim-hs-lsp

