---
- name: Set SSH authorized keys (for Vagrant)
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', item) }}"
  loop: "{{ user.ssh.authorized_keys|default[] }}"
  tags:
    - ssh_conf

- name: Install SSH private keys (for Vagrant)
  copy:
    src: "{{ item.src }}"
    dest: "/home/{{ user.name }}/.ssh/{{ item.name }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0600'
  loop: "{{ user.ssh.private_keys|default[] }}"
  tags:
    - ssh_conf

- name: Add known_hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.name }} {{ item.key }}"
    state: present
  become: yes
  become_user: "{{ user.name }}"
  loop: "{{ user.ssh.known_hosts|default([]) }}"
  tags:
    - ssh_conf
