# This file is generated by ansible. Do not edit manually.
# Edit $HOME/.zshenv.local instead.
source-if-exists() {
  [ -e $1 ] && . $1
}
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/usr/local/google-cloud-sdk/bin
source-if-exists $HOME/.ghcup/env
source-if-exists $HOME/.cargo/env
source-if-exists $HOME/.opam/opam-init/init.zsh
source-if-exists $HOME/.nix-profile/etc/profile.d/nix.sh
source-if-exists $HOME/.autojump/etc/profile.d/autojump.sh
source-if-exists $HOME/.zshenv.local
