- name: Install basic developement tools
  apt:
    name:
    - git
    - cvs
    - mercurial
    - subversion
    - fuse
    - vim
    - dnsutils
    - curl
    - wget
    - unzip
    - unar

- name: Set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: Ensure a locale exists
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present
