- name: Set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: Ensure a locale exists
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: Install basic developement tools
  apt:
    name:
    - git
    - cvs
    - mercurial
    - subversion
    - vim
    - unzip
    - dnsutils
    - zsh
    - fuse

- name: Set /etc/zsh/zprofile
  blockinfile:
    path: /etc/zsh/zprofile
    block: |
      if [ -d /etc/profile.d ]; then
       for i in /etc/profile.d/*.sh; do
         if [ -r $i ]; then
           . $i
         fi
       done
       unset i
      fi
