- name: Install oh-my-zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "/home/{{ user_name }}/.oh-my-zsh"

- name: Make oh-my-zsh owned by {{ user_name }}
  file:
    path: "/home/{{ user_name }}/.oh-my-zsh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory
    recurse: yes
  changed_when: false # TODO
