- name: Install zsh
  apt:
    name:
    - zsh

- name: Install oh-my-zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: /home/cq2n-iwym/.oh-my-zsh

- name: Make oh-my-zsh owned by cq2n-iwym
  file:
    path: /home/cq2n-iwym/.oh-my-zsh
    owner: cq2n-iwym
    group: cq2n-iwym
    state: directory
    recurse: yes
  changed_when: false # TODO
