- name: Install oh-my-zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "/home/{{ user.name }}/.oh-my-zsh"

- name: Make oh-my-zsh owned by {{ user.name }}
  file:
    path: "/home/{{ user.name }}/.oh-my-zsh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    recurse: yes
  changed_when: false # TODO

- name: Download fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "/home/{{ user.name }}/.fzf"
  register: download_fzf

- name: Make fzf owned by {{ user.name }}
  file:
    path: "/home/{{ user.name }}/.fzf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    recurse: yes
  changed_when: false # TODO

- name: Install fzf
  command:
    cmd: '/home/{{ user.name }}/.fzf/install --key-bindings --completion --no-update-rc'
  become: yes
  become_user: '{{ user.name }}'
  when: download_fzf.changed

