- name: Add the user "{{ user.name }}"
  user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    shell: /usr/bin/zsh
  when: user.create
  tags:
    - ensure_user

- name: Check if user "{{ user.name }}" exists
  getent:
    database: passwd
    key: "{{ user.name }}"
    fail_key: true
  tags:
    - ensure_user

- name: Ensure privilege attached to "{{ user.name }}"
  lineinfile:
    path: /etc/sudoers
    line: '{{ user.name }} ALL=(ALL) NOPASSWD:ALL'
    validate: /usr/sbin/visudo -cf %s
  when: user.sudoer
  tags:
    - ensure_user

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', user.ssh_public_key) }}"
  when: user.ssh_public_key is defined
  tags:
    - ensure_user

- name: Create ~/.local/bin
  file:
    path: "/home/{{ user.name }}/.local/bin"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  tags:
    - ensure_user
