- name: Install basic developement tools
  apt:
    name:
    - git
    - cvs
    - mercurial
    - subversion
    - fuse
    - vim
    - dnsutils
    - curl
    - wget
    - unzip
    - unar
  when: has_root
  tags:
    - tool

- name: Download awesome cli tools
  vars:
    dest: "{{ '/usr/local/bin' if has_root else '/home/'+user.name+'/.local/bin' }}"
  unarchive:
    src: "{{ item.url }}"
    dest: "{{ dest }}"
    creates: "{{ dest }}/{{ item.name }}"
    remote_src: true
    extra_opts:
      - --strip=1
      - --wildcards
      - "*/{{  item.name }}"
  loop:
    - name: "rg"
      url: "https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep-12.1.1-x86_64-unknown-linux-musl.tar.gz"
    - name: "bat"
      url: "https://github.com/sharkdp/bat/releases/download/v0.17.1/bat-v0.17.1-x86_64-unknown-linux-musl.tar.gz"
    - name: "fd"
      url: "https://github.com/sharkdp/fd/releases/download/v8.2.1/fd-v8.2.1-i686-unknown-linux-musl.tar.gz"
  tags:
    - tool
