- name: Check whether Node.js is installed
  shell:
    cmd: which node
  register: which_node
  changed_when: false
  ignore_errors: true
  tags:
    - javascript

- name: Add Node.js PPA
  shell:
    cmd: curl -sL https://deb.nodesource.com/setup_14.x | sh
    warn: false
  when: "not which_node.skipped|default(false) and which_node.rc != 0"
  tags:
    - javascript

- name: Install Node.js
  apt:
    name:
      - nodejs
  when: "not which_node.skipped|default(false) and which_node.rc != 0"
  tags:
    - javascript
