- name: Set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
  when: has_root
  tags:
    - basic

- name: Ensure a locale exists
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present
  when: has_root
  tags:
    - basic
