- name: Add the user "{{ user_name }}"
  user:
    name: "{{ user_name }}"
    password: "$6$mysecretsalt$AtKHRdMmHc24tTS6fTA/JslpXufZKYtQQ1JNZyueUJzzSdDsoIZniPEZqOSCRYQ8sPI6Z1Pu4tk8FW5rRykzE."
    shell: /usr/bin/zsh

- name: Ensure privilege attached to "{{ user_name }}"
  lineinfile:
    path: /etc/sudoers
    line: '{{ user_name }} ALL=(ALL) NOPASSWD:ALL'
    validate: /usr/sbin/visudo -cf %s

- name: Create ~/.ssh
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0700'

- name: Copy ssh public key
  copy:
    src: "/c/Users/{{ user_name }}/.ssh/id_ed25519.pub"
    dest: "/home/{{ user_name }}/.ssh/id_ed25519.pub"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'

- name: Copy ssh private key
  copy:
    src: "/c/Users/{{ user_name }}/.ssh/id_ed25519"
    dest: "/home/{{ user_name }}/.ssh/id_ed25519"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'

- name: Set authorized_keys for ssh from host
  blockinfile:
    block: "{{ lookup('file', '/c/Users/' + user_name + '/.ssh/id_ed25519.pub') }}"
    path: "/home/{{ user_name }}/.ssh/authorized_keys"
    create: yes
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'
