- name: Add the user 'cq2n-iwym'
  user:
    name: cq2n-iwym
    password: "$6$mysecretsalt$AtKHRdMmHc24tTS6fTA/JslpXufZKYtQQ1JNZyueUJzzSdDsoIZniPEZqOSCRYQ8sPI6Z1Pu4tk8FW5rRykzE."
    shell: /usr/bin/zsh

- name: Ensure privilege attached to 'cq2n-iwym'
  lineinfile:
    path: /etc/sudoers
    line: 'cq2n-iwym ALL=(ALL) NOPASSWD:ALL'
    validate: /usr/sbin/visudo -cf %s

- name: Create ~/.ssh
  file:
    path: /home/cq2n-iwym/.ssh
    state: directory
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0700'

- name: Copy ssh public key
  copy:
    src: /c/Users/cq2n-iwym/.ssh/id_ed25519.pub
    dest: /home/cq2n-iwym/.ssh/id_ed25519.pub
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0600'

- name: Copy ssh private key
  copy:
    src: /c/Users/cq2n-iwym/.ssh/id_ed25519
    dest: /home/cq2n-iwym/.ssh/id_ed25519
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0600'

- name: Set authorized_keys for ssh from host
  blockinfile:
    block: "{{ lookup('file', '/c/Users/cq2n-iwym/.ssh/id_ed25519.pub') }}"
    path: /home/cq2n-iwym/.ssh/authorized_keys
    create: yes
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0600'
