- name: Set dotfiles
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user.name }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'
  loop:
    - .zprofile
    - .zshrc
    - .zshenv
    - .zsh_aliases
  tags:
    - zsh

- name: Check if oh-my-zsh is installed
  stat:
    path: "/home/{{ user.name }}/.oh-my-zsh"
  register: omz
  tags:
    - zsh

- name: Install oh-my-zsh
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "/home/{{ user.name }}/.oh-my-zsh"
  when: not omz.stat.isdir|default(false)
  tags:
    - zsh

- name: Make oh-my-zsh owned by {{ user.name }}
  file:
    path: "/home/{{ user.name }}/.oh-my-zsh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    recurse: yes
  changed_when: false # TODO
  tags:
    - zsh

- name: Check if fzf is installed
  stat:
    path: "/home/{{ user.name }}/.fzf"
  register: fzf
  tags:
    - zsh

- name: Download fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "/home/{{ user.name }}/.fzf"
  register: download_fzf
  when: not fzf.stat.isdir|default(false)
  tags:
    - zsh

- name: Make fzf owned by {{ user.name }}
  file:
    path: "/home/{{ user.name }}/.fzf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    recurse: yes
  changed_when: false # TODO
  tags:
    - zsh

- name: Install fzf
  command:
    cmd: 'sudo -u {{ user.name }} /home/{{ user.name }}/.fzf/install --key-bindings --completion --no-update-rc'
    warn: false
  when: download_fzf.changed|default(false)
  tags:
    - zsh
