- set_fact:
    is_stretch: "{{ ansible_distribution_release == 'stretch' }}"

- debug:
    var: is_stretch

- debug:
    var: ansible_distribution_release

- name: Install build tools
  apt:
    name:
    - ant
    - gradle

- name: Install OpenJDK8 (stretch only)
  apt:
    name:
      - openjdk-8-jdk-headless
  when: is_stretch

- name: Install AdoptOpenJDK
  vars:
    adopt_openjdk8: "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u282-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u282b08.tar.gz"
    adopt_openjdk11: "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz"
    targets: "{{ [ adopt_openjdk11 ] if is_stretch else [ adopt_openjdk8, adopt_openjdk11 ]}}"
  unarchive:
    src: "{{ item }}"
    dest: "/usr/lib/jvm"
    remote_src: true
  loop: "{{ targets }}"

- name: Prepare install directory for jdt.ls
  file:
    path: /usr/local/share/jdt-language-server
    state: directory

- name: Install jdt.ls
  unarchive:
    src: https://ftp.yz.yamagata-u.ac.jp/pub/eclipse/jdtls/snapshots/jdt-language-server-latest.tar.gz
    dest: /usr/local/share/jdt-language-server
    remote_src: true

- name: Set permission of jdt.ls
  file:
    path: /usr/local/share/jdt-language-server
    recurse: yes
    mode: '777'
  changed_when: false

- name: Configure Environment varibales
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    mode: "644"
  loop:
    - etc/profile.d/java.sh
