---
- name: Add a setting to ~/.gitconfig
  community.general.git_config:
    scope: global
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  become: yes
  become_user: "{{ user.name }}"
  loop:
    - key: user.email
      value: "{{ user.git.email }}"
    - key: user.name
      value: "{{ user.git.name }}"
    - key: merge.ff
      value: "false"
    - key: merge.conflictstyle
      value: "diff3"
    - key: core.pager
      value: "LESSCHARSET=utf-8 less"
  tags:
    - git
    - git_conf

- name: Add Git hosting server to known_hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.name }} {{ item.key }}"
    state: present
  become: yes
  become_user: "{{ user.name }}"
  loop: "{{ user.git.hosts|default([]) }}"
  tags:
    - git
    - git_conf

- name: Checkout git repositories
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
  become: yes
  become_user: "{{ user.name }}"
  loop: "{{ user.git.repositories|default([]) }}"
  tags:
    - git
    - git_conf
