---
- name: Configure ~/.gitconfig
  community.general.git_config:
    scope: global
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  become: yes
  become_user: "{{ user.name }}"
  loop: "{{ user.git.config | default({}) | dict2items }}"
  tags:
    - git
    - git_conf

- name: Checkout git repositories
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
  become: yes
  become_user: "{{ user.name }}"
  loop: "{{ user.git.repositories|default([]) }}"
  tags:
    - git
    - git_conf
