- name: Install ghcup dependencies
  apt:
    name:
      - build-essential
      - curl
      - libffi-dev
      - libgmp-dev
      - libncurses-dev
      - libtinfo-dev
  tags:
    - haskell
  when: haskell.install_ghcup|default(false)

- name: Install ghcup
  environment:
    # TODO configure
    BOOTSTRAP_HASKELL_NONINTERACTIVE: "1"
    BOOTSTRAP_HASKELL_NO_UPGRADE: "1"
    BOOTSTRAP_HASKELL_GHC_VERSION: "8.10.4"
  shell:
    cmd: "curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sudo -E -u {{ user.name }} sh"
  command:
    cmd: "/tmp/get-ghcup.sh"
    creates: "/home/{{ user.name }}/.ghcup"
  tags:
    - haskell
  when: haskell.install_ghcup|default(false) # totemo jikan kakaru

- name: Instal nix
  shell:
    cmd: "curl -L https://nixos.org/nix/install | sh"
    creates: "/home/{{ user.name }}/.nix-profile"
    warn: false
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - haskell
  when: haskell.install_nix|default(false)
