- name: Install tmux dependencies
  apt:
    name:
      - automake
      - pkg-config
      - bison
      - libevent-dev
      - xsel

- name: Clone tmux
  git:
    repo: 'https://github.com/tmux/tmux.git'
    dest: /root/tmux

- name: Install tmux
  shell:
    chdir: /root/tmux
    cmd: |
      ./autogen.sh
      ./configure
      make -j4
      sudo make install
    creates: /usr/local/bin/tmux

- name: Create ~/Repos
  file:
    path: "/home/{{ user_name }}/Repos"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'

- name: Clone tmux-logging
  git:
    repo: 'https://github.com/tmux-plugins/tmux-logging.git'
    dest: "/home/{{ user_name }}/Repos/tmux-logging"

- name: Set .tmux.conf
  copy:
    src: tmux.conf
    dest: "/home/{{ user_name }}/.tmux.conf"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'
