- name: Install tmux dependencies
  apt:
    name:
      - automake
      - pkg-config
      - bison
      - libevent-dev
      - libncurses-dev
      - xsel
  # TODO meta/main.ymlとかでinstall_method変数を定義する
  when: tmux.install_method|default("apt") == "build"

- name: Clone tmux
  git:
    repo: 'https://github.com/tmux/tmux.git'
    dest: /root/tmux
  when: tmux.install_method|default("apt") == "build"

- name: Install tmux
  shell:
    chdir: /root/tmux
    cmd: |
      ./autogen.sh
      ./configure
      make -j4
      sudo make install
    creates: /usr/local/bin/tmux
  when: tmux.install_method|default("apt") == "build"

- name: Install tmux (apt)
  apt:
    name:
      - tmux
  when: tmux.install_method|default("apt") == "apt"

- name: Download tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "/home/{{ user.name }}/.tmux/plugins/tpm"
  register: download_tpm

- name: Make ~/.tmux owned by {{ user.name }}
  file:
    path: "/home/{{ user.name }}/.tmux"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    recurse: yes
  changed_when: false # TODO

- name: Set .tmux.conf
  copy:
    src: tmux.conf
    dest: "/home/{{ user.name }}/.tmux.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'
