- name: Check whether tmux is installed
  shell:
    cmd: which tmux
  register: which_tmux
  changed_when: false
  ignore_errors: true

- name: Install tmux dependencies
  apt:
    name:
      - automake
      - pkg-config
      - bison
      - libevent-dev
      - libncurses-dev
      - xsel
  when: "tmux.install_method|default('apt') == 'build' and
         not which_tmux.skipped|default(false) and which_tmux.rc != 0"

- name: Clone tmux
  git:
    repo: 'https://github.com/tmux/tmux.git'
    dest: /root/tmux
  when: "tmux.install_method|default('apt') == 'build' and
         not which_tmux.skipped|default(false) and which_tmux.rc != 0"

- name: Install tmux
  shell:
    chdir: /root/tmux
    cmd: |
      ./autogen.sh
      ./configure
      make -j4
      sudo make install
    creates: /usr/local/bin/tmux
  when: "tmux.install_method|default('apt') == 'build' and
         not which_tmux.skipped|default(false) and which_tmux.rc != 0"

- name: Install tmux (apt)
  apt:
    name:
      - tmux
  when: "tmux.install_method|default('apt') == 'apt' and
         not which_tmux.skipped|default(false) and which_tmux.rc != 0"

- name: Check if tpm is installed
  stat:
    path: "/home/{{ user.name }}/.tmux/plugins/tpm"
  register: tpm

- name: Download tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "/home/{{ user.name }}/.tmux/plugins/tpm"
  register: download_tpm
  when: not tpm.stat.isdir|default(false)

- name: Make ~/.tmux owned by {{ user.name }}
  file:
    path: "/home/{{ user.name }}/.tmux"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    recurse: yes
  changed_when: false # TODO

- name: Set .tmux.conf
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user.name }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'
  loop:
    - .tmux.conf
