- name: Install tmux dependencies
  apt:
    name:
      - automake
      - pkg-config
      - bison
      - libevent-dev
      - xsel

- name: Clone tmux
  git:
    repo: 'https://github.com/tmux/tmux.git'
    dest: /root/tmux

- name: Install tmux
  shell:
    chdir: /root/tmux
    cmd: |
      ./autogen.sh
      ./configure
      make -j4
      sudo make install
    creates: /usr/local/bin/tmux

- name: Create ~/Repos
  file:
    path: /home/cq2n-iwym/Repos
    state: directory
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0755'

- name: Clone tmux-logging
  git:
    repo: 'https://github.com/tmux-plugins/tmux-logging.git'
    dest: /home/cq2n-iwym/Repos/tmux-logging

- name: Set .tmux.conf
  copy:
    src: tmux.conf
    dest: /home/cq2n-iwym/.tmux.conf
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0644'
