- name: Install user scripts
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user.name }}/.local/bin/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    - 'with-log'
    - 'nvr-git'
    - 'vifm-viewer'
    - 'vifm-fzf'
  tags:
    - user_script

- name: Install ~/local/bin/myclip
  template:
    src: myclip.j2
    dest: "/home/{{ user.name }}/.local/bin/myclip"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  when: false # TODO
  tags:
    - user_script
