- name: Set ~/local/bin/with-log
  copy:
    src: with-log
    dest: "/home/{{ user.name }}/.local/bin/with-log"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  tags:
    - user_script

- name: Set ~/local/bin/myclip
  template:
    src: myclip.j2
    dest: "/home/{{ user.name }}/.local/bin/myclip"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  when: false # TODO
  tags:
    - user_script
