- name: Install user scripts
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user.name }}/.local/bin/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  loop:
    - 'with-log'
    - 'myclip'
    - 'nvr-git'
  tags:
    - user_script
