---
# based on https://docs.docker.com/engine/install/debian

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  tags:
    - docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags:
    - docker

- name: Add Docker Repository
  vars:
    dist: "{{ ansible_distribution | lower }}"
    code_name: "{{ ansible_distribution_release }}"
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ dist }} {{ code_name }} stable"
    state: present
  tags:
    - docker

- name: Update apt and install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: latest

- name: Install Docker Module for Python
  pip:
    name:
      - docker
      - docker-compose
    executable: "{{ pip_cmd }}"
  tags:
    - docker

- name: "Add user {{ user.name }} to docker group"
  user:
    name: "{{ user.name }}"
    append: yes
    groups:
      - docker
