- name: Download neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: "/home/{{ user_name }}/.local/bin/nvim"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'

- name: Create ~/.config/nvim/autoload
  file:
    path: "/home/{{ user_name }}/.config/nvim/autoload"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user_name }}/.config/nvim/autoload/plug.vim"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'

- name: Install .config/nvim
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user_name }}/{{ item }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 'preserve'
  loop:
    - .config/nvim/

- name: Install neovim-remote
  pip:
    name: neovim-remote
  ignore_errors: true

- name: Install pynvim
  pip:
    name: pynvim
  ignore_errors: true

- name: Install neovim/node-client
  community.general.npm:
    name: neovim
    global: yes
