- name: Create ~/.local/bin
  file:
    path: /home/cq2n-iwym/.local/bin
    state: directory
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0755'

- name: Download neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /home/cq2n-iwym/.local/bin/nvim
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0755'

- name: Create ~/.config/nvim/autoload
  file:
    path: /home/cq2n-iwym/.config/nvim/autoload
    state: directory
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0755'

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/cq2n-iwym/.config/nvim/autoload/plug.vim
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0644'

- name: Install init.vim
  copy:
    src: init.vim
    dest: /home/cq2n-iwym/.config/nvim/init.vim
    owner: cq2n-iwym
    group: cq2n-iwym
    mode: '0644'

- name: Install neovim-remote
  pip:
    name: neovim-remote
    executable: pip3.8

- name: Install pynvim
  pip:
    name: pynvim
    executable: pip3.8

- name: Install neovim/node-client
  community.general.npm:
    name: neovim
    global: yes
