- name: Create ~/.local/bin
  file:
    path: "/home/{{ user_name }}/.local/bin"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'

- name: Download neovim
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: "/home/{{ user_name }}/.local/bin/nvim"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'

- name: Create ~/.config/nvim/autoload
  file:
    path: "/home/{{ user_name }}/.config/nvim/autoload"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user_name }}/.config/nvim/autoload/plug.vim"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'

- name: Install init.vim
  copy:
    src: init.vim
    dest: "/home/{{ user_name }}/.config/nvim/init.vim"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'

- name: Install neovim-remote
  pip:
    name: neovim-remote
    executable: pip3.8
  ignore_errors: true

- name: Install pynvim
  pip:
    name: pynvim
    executable: pip3.8
  ignore_errors: true

- name: Install neovim/node-client
  community.general.npm:
    name: neovim
    global: yes
