- name: Install neovim (system)
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: "/usr/local/bin/nvim"
    mode: '0755'
  when: has_root
  tags:
    - neovim

- name: Install neovim (user local)
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: "/home/{{ user.name }}/.local/bin/nvim"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0755'
  when: not has_root
  tags:
    - neovim
